import { useMemo, useState } from 'react'
import jsPDF from 'jspdf'
import { RefreshCw, Download, CalendarDays, Save, LoaderCircle } from 'lucide-react'
import api, { apiErrorMessage } from '../api'
import { useAuth } from '../auth'
import { slotAssignments, cellText, getCourseColor, downloadBlob } from './helpers'

/**
 * The timetable view.
 *
 * - owner/admin: generate a fresh schedule with the constraint solver,
 *   publish it to the institution (saved as a tenant Timetable document),
 *   export PDF / iCal, and filter the grid by section.
 * - faculty/student: read-only view of the most recent published timetable
 *   (enforced by backend RBAC — this page simply renders what it may see).
 */
export default function SchedulePage({
  data,
  planner,
  days,
  times,
  metrics,
  isGenerating,
  onGenerate,
  notify,
  fail,
}) {
  const { isAdmin, user } = useAuth()
  const [isExportingPdf, setIsExportingPdf] = useState(false)
  const [sectionFilter, setSectionFilter] = useState('all')
  const [isPublishing, setIsPublishing] = useState(false)

  const schedule = data?.schedule

  // Distinct sections present in the schedule, for client-side filtering.
  const sections = useMemo(() => {
    const found = new Set()
    ;(schedule?.assignments || []).forEach((item) => (item.sections || []).forEach((s) => found.add(s)))
    return [...found].sort()
  }, [schedule])

  const visibleSchedule = useMemo(() => {
    if (!schedule) return null
    if (sectionFilter === 'all') return schedule
    return {
      ...schedule,
      assignments: (schedule.assignments || []).filter((item) => item.sections?.includes(sectionFilter)),
    }
  }, [schedule, sectionFilter])

  async function exportIcal() {
    if (!visibleSchedule) return
    try {
      const response = await api.post(
        '/export/ical',
        { schedule: visibleSchedule, calendarName: `${planner.campusName} Timetable` },
        { responseType: 'text' },
      )
      downloadBlob(response.data, 'ScheduleAI.ics', 'text/calendar;charset=utf-8')
      notify('Calendar exported successfully.')
    } catch (requestError) {
      fail(apiErrorMessage(requestError, 'iCal export failed.'))
    }
  }

  async function publishTimetable() {
    if (!data?.parsed || !schedule) return
    setIsPublishing(true)
    try {
      await api.post('/timetables/from-schedule', {
        name: `${planner.campusName} — ${new Date().toLocaleDateString()}`,
        parsed: data.parsed,
        schedule,
      })
      notify('Published! Faculty and students at your institution can now view this timetable.')
    } catch (requestError) {
      fail(apiErrorMessage(requestError, 'Could not publish the timetable.'))
    } finally {
      setIsPublishing(false)
    }
  }

  async function exportPdf() {
    if (!visibleSchedule) return
    setIsExportingPdf(true)
    try {
      const pdf = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' })
      const pageWidth = pdf.internal.pageSize.getWidth()
      const pageHeight = pdf.internal.pageSize.getHeight()
      const margin = 24
      const headerHeight = 56
      const timeColWidth = 70
      const gridWidth = pageWidth - margin * 2
      const colWidth = (gridWidth - timeColWidth) / days.length
      const rowHeight = Math.max(76, Math.floor((pageHeight - margin * 2 - headerHeight) / (times.length + 1)))

      pdf.setFillColor(10, 18, 34)
      pdf.rect(0, 0, pageWidth, pageHeight, 'F')
      pdf.setTextColor(255, 255, 255)
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(20)
      pdf.text(`${planner.campusName} Weekly Timetable`, margin, 34)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(10)
      pdf.setTextColor(190, 200, 220)
      if (sectionFilter !== 'all') {
        pdf.text(`Section filter: ${sectionFilter}`, margin, 50)
      } else {
        pdf.text('Generated by ScheduleAI', margin, 50)
      }

      const gridTop = margin + headerHeight
      pdf.setDrawColor(190, 200, 220)

      pdf.roundedRect(margin, gridTop, timeColWidth, rowHeight, 8, 8, 'FD')
      pdf.setTextColor(70, 85, 110)
      pdf.setFont('helvetica', 'bold')
      pdf.text('Time', margin + 20, gridTop + 22)

      days.forEach((day, index) => {
        const left = margin + timeColWidth + index * colWidth
        pdf.roundedRect(left, gridTop, colWidth - 6, rowHeight, 8, 8, 'FD')
        pdf.text(day, left + 12, gridTop + 22)
      })

      times.forEach((time, rowIndex) => {
        const rowTop = gridTop + rowHeight + rowIndex * rowHeight
        pdf.setFillColor(255, 255, 255)
        pdf.roundedRect(margin, rowTop, timeColWidth, rowHeight - 6, 8, 8, 'FD')
        pdf.setTextColor(70, 85, 110)
        pdf.setFontSize(10)
        pdf.text(time, margin + 16, rowTop + 20)

        days.forEach((day, colIndex) => {
          const left = margin + timeColWidth + colIndex * colWidth
          pdf.setFillColor(255, 255, 255)
          pdf.roundedRect(left, rowTop, colWidth - 6, rowHeight - 6, 8, 8, 'FD')
          pdf.setTextColor(30, 41, 59)
          pdf.setFont('helvetica', 'normal')
          pdf.setFontSize(8)
          const text = cellText(visibleSchedule, day, time)
          pdf.text(text, left + 10, rowTop + 16, { maxWidth: colWidth - 22, lineHeightFactor: 1.15 })
        })
      })

      pdf.save('ScheduleAI-timetable.pdf')
      notify('PDF exported successfully.')
    } catch {
      fail('PDF export failed. Generate the timetable again and retry.')
    } finally {
      setIsExportingPdf(false)
    }
  }

  return (
    <main className="min-h-screen" style={{ backgroundColor: '#2a2d3a' }}>
      <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
        {!isAdmin && user ? (
          <div className="mb-6 glass-elevated p-6 rounded-lg">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 rounded-full bg-gradient-to-br from-blue-400 to-purple-500 flex items-center justify-center text-white font-bold text-lg">
                {user.name?.charAt(0)?.toUpperCase() || '?'}
              </div>
              <div>
                <h3 className="text-lg font-bold text-white">{user.name}</h3>
                <p className="text-sm text-slate-400">
                  {user.email} • viewing as <span className="uppercase tracking-wide">{user.role}</span>
                </p>
              </div>
            </div>
          </div>
        ) : null}

        <div className="glass-elevated p-6 animate-fade-in-up">
          <div className="mb-5 flex flex-wrap items-center justify-between gap-3">
            <div>
              <p className="text-sm font-medium" style={{ color: '#94a3b8' }}>Weekly timetable</p>
              <h2 className="font-['Space_Grotesk',sans-serif] text-2xl" style={{ color: '#e2e8f0' }}>
                {isAdmin ? 'Generated schedule' : 'Published schedule'}
              </h2>
            </div>
            <div className="flex flex-wrap gap-3">
              {isAdmin && (
                <>
                  <button
                    type="button"
                    onClick={onGenerate}
                    disabled={isGenerating}
                    className="skeu-button-glossy inline-flex items-center gap-2 disabled:opacity-60"
                  >
                    {isGenerating ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
                    Generate timetable
                  </button>
                  <button
                    type="button"
                    onClick={publishTimetable}
                    disabled={!schedule || isPublishing}
                    className="skeu-button-premium inline-flex items-center gap-2 disabled:opacity-50"
                  >
                    {isPublishing ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                    Publish to institution
                  </button>
                </>
              )}
              <button
                type="button"
                onClick={exportPdf}
                disabled={!visibleSchedule || isExportingPdf}
                className="glass-button inline-flex items-center gap-2 disabled:opacity-50"
              >
                <Download className="h-4 w-4" />
                {isExportingPdf ? 'Exporting...' : 'PDF'}
              </button>
              <button
                type="button"
                onClick={exportIcal}
                disabled={!visibleSchedule}
                className="glass-button inline-flex items-center gap-2 disabled:opacity-50"
              >
                <CalendarDays className="h-4 w-4" />
                iCal
              </button>
            </div>
          </div>

          {metrics && Object.keys(metrics).length > 0 ? (
            <div className="mb-4 flex flex-wrap gap-3 text-xs" style={{ color: '#94a3b8' }}>
              <span className="glass-cyan px-3 py-1 rounded-full">
                {metrics.scheduledSessions ?? 0}h scheduled
              </span>
              <span className="glass-orange px-3 py-1 rounded-full">
                {metrics.unscheduledSessions ?? 0}h pending
              </span>
              <span className="glass-green px-3 py-1 rounded-full">
                satisfaction {metrics.satisfactionScore ?? 0}%
              </span>
            </div>
          ) : null}

          {/* Section filter */}
          {sections.length > 0 ? (
            <div className="mb-4 flex flex-wrap items-center gap-2">
              <span className="text-xs uppercase tracking-widest" style={{ color: '#64748b' }}>Section</span>
              <button
                type="button"
                onClick={() => setSectionFilter('all')}
                className={`text-xs px-3 py-1.5 rounded-full transition ${sectionFilter === 'all' ? 'glass-cyan' : 'glass-button'}`}
                style={{ color: sectionFilter === 'all' ? '#e2e8f0' : '#94a3b8' }}
              >
                All
              </button>
              {sections.map((section) => (
                <button
                  key={section}
                  type="button"
                  onClick={() => setSectionFilter(section)}
                  className={`text-xs px-3 py-1.5 rounded-full transition ${sectionFilter === section ? 'glass-cyan' : 'glass-button'}`}
                  style={{ color: sectionFilter === section ? '#e2e8f0' : '#94a3b8' }}
                >
                  {section}
                </button>
              ))}
            </div>
          ) : null}

          <div className="glass-cyan overflow-hidden p-4">
            {visibleSchedule ? (
              <div className="overflow-x-auto">
                <table className="min-w-full border-separate border-spacing-2 text-left">
                  <thead>
                    <tr>
                      <th className="glass-purple p-3 text-sm font-medium rounded-lg" style={{ color: '#9ca3af' }}>Time</th>
                      {days.map((day) => (
                        <th key={day} className="glass-cyan p-3 text-sm font-medium rounded-lg" style={{ color: '#a1a5b0' }}>
                          {day}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {times.map((time) => {
                      if (time === '13:00') {
                        return (
                          <tr key="lunch-break">
                            <td
                              colSpan={days.length + 1}
                              className="rounded-lg px-4 py-4 text-center text-sm font-semibold animate-glow-pulse"
                              style={{
                                backgroundColor: 'rgba(209, 213, 219, 0.2)',
                                color: '#d1d5db',
                                border: '2px solid rgba(209, 213, 219, 0.4)',
                              }}
                            >
                              LUNCH BREAK (12:00-13:00)
                            </td>
                          </tr>
                        )
                      }

                      return (
                        <tr key={time}>
                          <td className="glass-purple p-4 text-sm font-medium rounded-lg" style={{ color: '#9ca3af' }}>{time}</td>
                          {days.map((day) => {
                            const items = slotAssignments(visibleSchedule, day, time)
                            return (
                              <td key={`${day}-${time}`} className="align-top">
                                <div className="min-h-28 space-y-2 rounded-lg p-3 glass-green">
                                  {items.length
                                    ? items.map((item, index) => {
                                        const colors = getCourseColor(item.id, index)
                                        return (
                                          <div
                                            key={item.id}
                                            className="rounded-lg px-3 py-2 text-xs shadow-sm animate-scale-in"
                                            style={{
                                              backgroundColor: colors.bg,
                                              border: `2px solid ${colors.border}`,
                                              color: colors.text,
                                            }}
                                          >
                                            <p className="font-bold text-sm">{item.courseName}</p>
                                            <p className="mt-1 font-semibold">{item.room}</p>
                                            <p className="mt-1 text-xs">{item.faculty}</p>
                                            <p className="mt-1 text-[10px] opacity-75">{item.sections.join(', ')}</p>
                                          </div>
                                        )
                                      })
                                    : null}
                                </div>
                              </td>
                            )
                          })}
                        </tr>
                      )
                    })}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="grid min-h-80 place-items-center text-sm text-center px-6" style={{ color: '#94a3b8' }}>
                {isAdmin
                  ? 'No schedule yet — press "Generate timetable" to run the constraint solver.'
                  : 'Nothing published yet. Your institution owner/admin needs to generate and publish a timetable.'}
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  )
}
